---
title: "Prepae metadata file for asthma data"
author: "TB"
date: "7/28/2017"
output: html_document
---
```{r}
library("tidyverse")
library("stringr")
library("readr")
library("plotly")
library("ggplot2")
library("neutrominer")
library("magrittr")
library("caret")
library("AppliedPredictiveModeling")
```

# Load data
Analysis folder and tracked data 
```{r}
analysis_folder <- "../../analysis/sample/20170927_cp3/"
csv_profile <- 'profiles.csv'
csv_single_cells <- 
population <- read_csv(file.path(analysis_folder, csv_profile)) %>% 
  filter(Metadata_condition == "asthma" | Metadata_condition == "control-asthma") %>%
  filter(Metadata_attractant == "ltb4") %>%
  filter( !((Metadata_id == "kira453") & (Metadata_date == "201612b")) ) %>%
  filter( !((Metadata_id == "kira095") & (Metadata_date == "201612b")) ) %>%
  filter( !((Metadata_id == "kira094") & (Metadata_date == "201612b"))) %>%
  filter( !((Metadata_date == "201612a") & (Metadata_id == "kira099") ) ) %>%
  filter( !((Metadata_date == "201612b") & (Metadata_id == "kira099") ) ) %>%
  filter( !((Metadata_date == "201612") & (Metadata_id == "kira462") & (Metadata_concentration == "1ul") ) ) %>%
  filter(complete.cases(.))
```
# Metadata 
```{r}
strata <- c('Metadata_attractant','Metadata_concentration','Metadata_condition',
            'Metadata_date','Metadata_dose','Metadata_id')
```


Aggregate data for each experiment
```{r}
feature_cols <- base::setdiff(
  colnames(population) %>%
    stringr::str_subset("^Area|^Radial"),
  colnames(population) %>%
    stringr::str_subset("_1")
)


aggregated <-
  cytominer::aggregate(
    population = population,
    variables = feature_cols,
    strata = strata
  )
```

```{r}
asthma <- aggregated %>% 
  ungroup() %>%
  dplyr::select_(.dots = c("Metadata_condition", feature_cols )) %>%
  dplyr::mutate(Metadata_condition = as.factor(Metadata_condition)) %>%
  dplyr::rename(class = Metadata_condition) %>%
  dplyr::select(
    -AreaShape_Center_Z, 
    -AreaShape_EulerNumber, 
    -RadialDistribution_ZernikeMagnitude_neutrosIlluCorrected_9_9, 
    -RadialDistribution_ZernikePhase_neutrosIlluCorrected_0_0, 
    -RadialDistribution_ZernikeMagnitude_neutrosIlluCorrected_7_7,
    -RadialDistribution_ZernikeMagnitude_neutrosIlluCorrected_8_8
    )
  
```
Create simple test data set 
```{r}
set.seed(768)

train_control = trainControl(method = "LOOCV")
  
lda_model <- train(class~., data = asthma, 
                 method = "lda2", 
                 trControl = train_control,
                 verbose = FALSE)
lda_model
```